### ISSUE TITLE
session should support (host, apiKey)

### ISSUE THREAD

**Issue by rexshang** [scottdware/go-panos#10]
Currently, the NewSession method takes host, login and passwd as parameters.  Keeping passwd in clear text is against my company's policy.  I am wondering if we can have another way to create the session.  PANOS does support ApiKey as part of their standard interface.  And I can see that internal to go-panos, the ApiKey is also used.  Can we have a new session interface based on host and ApiKey?

**Comment by scottdware** [comment]
Hi,

I will definitely work at getting this added. I'll work at it today and test it.

**Comment by rexshang** [comment]
This is great!  Thank you.

Rex

**Comment by scottdware** [comment]
Rex,

I just committed a change which should take care of this. I also updated the README with examples of how to use it.

**Comment by rexshang** [comment]
I just saw the code update.  Nice!

Rex
