### ISSUE TITLE
error importing objects

### ISSUE THREAD

**Issue by Youness-ezz** [scottdware/go-panos#20]
Hi ;
I'm trying to import objects to PA FW but I'm getting issues with the folwing error messages 

2021/09/22 22:22:24 Running actions on 52 lines - this might take a few of minutes if you have a lot of objects
panic: runtime error: index out of range [5] with length 1

goroutine 1 [running]:
github.com/scottdware/panco/cmd.glob..func5(0x1b82e80, {0x176272e, 0x6, 0x6})
        C:/Users/sware004/Documents/Github/panco/cmd/objects_import.go:78 +0x8d4a
github.com/spf13/cobra.(*Command).execute(0x1b82e80, {0xc000052a20, 0x6, 0x6})
        C:/Users/sware004/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0x1b81080)
        C:/Users/sware004/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
        C:/Users/sware004/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/scottdware/panco/cmd.Execute()
        C:/Users/sware004/Documents/Github/panco/cmd/root.go:142 +0x25
main.main()
        C:/Users/sware004/Documents/Github/panco/main.go:26 +0x17

can you help me fix this .
best regards

**Comment by scottdware** [comment]
Are you running panco from the actual binary executable? Can you share with me the CSV file you’re using so I can take a look?
