### ISSUE TITLE
unsupported protocol scheme ""

### ISSUE THREAD

**Issue by irom77** [scottdware/go-panos#5]
Not sure what I am doing wrong:

```
pan1 := PaloAlto{
			Host: "192.168.3.101",
			Key: "XXX",  // api key omitted
		}
		err := pan1.CreateAddress("dummy","ip","1.2.3.4/32","", false)
		if err != nil {
			log.Fatal(err)
		}
```

Says (removed api key from output): 

```
2017/03/21 08:48:38 Post ?action=set&element=%3Cip-netmask%3E1.2.3.4%2F32%3C%2Fip-netmask%3E&key=XXX&type=config&xpath=: unsupported protocol scheme ""
exit status 1
```

**Comment by scottdware** [comment]
Ok, I'll have a look.

**Comment by irom77** [comment]
I'm trying the same with curl, not sure if xpath below is correct but it does not work too ;)

`curl -k 'https://192.168.3.101/api/type=config&action=set&key=XXX&xpath=/config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/address/entry[@name='dummy']<ip-netmask>'1.1.1.1/32'</ip-netmask>'`

curl: (3) [globbing] bad range specification in column 159

**Comment by scottdware** [comment]
On your initial comment, how are you establishing a session? Based on what you posted, it doesn't look correct. It should be like:

```Go
// Parameters are host, user, password
pan1 := panos.NewSession("firewall.yourcompany.com", "admin", "paloalto")
err := pan1.CreateAddress("dummy", "ip", "1.2.3.4/32", "", false)
if err != nil {
    fmt.Println(err)
}
```

Can you try that and let me know how it goes? Also, your curl script won't work because you have to post the actual XML as the body of the request.

**Comment by irom77** [comment]
That worked like a charm..thank you very much, appreciate. I didn't know I have to create session, I thought I can use CreateAddress() method on that PaloAlto struct (without credentials, thru api key only). But now it looks like I don't need that struct at all. Just curious, what is that struct for ? 
```
/*pan1 := PaloAlto{
			Host: "192.168.3.101",
			Key: "XXX",
		}*/
		pan1session, _ := NewSession("192.168.3.101", "admin", "password")
		pan1session.CreateAddress("dummy","ip","1.2.3.4/32","", false)
```
		
I love it anyways;) Btw , tested with PANOS 8.0

**Comment by scottdware** [comment]
Glad it worked for you! So, you brought up a good idea, and I think I'm going to add some basic examples to the README file. That way on the main page, people can quickly see how to use it (or at least, establish a session).

The `PaloAlto` struct is what holds the session information for the device (API key that was generated, platform, software version, etc.). I'll update the main README by tomorrow.
