### ISSUE TITLE
Panorama - Operation failed - A descriptive error message is returned in the response

### ISSUE THREAD

**Issue by irom77** [scottdware/go-panos#6]
Now I am trying to repeat this on Panorama in the device group MR-DC1-PROD (not as shared object)

```
pan1session, _ := NewSession(host, login, Password)		
pan1session.CreateAddressFromCsv("address-sample.csv", false, "MR-DC1-PROD")
```
		
This works on firewall (I am only changing IP address), but on Panorama gives an error:

```
2017/03/22 08:14:50 error code 13: Operation failed - A descriptive error message is returned in the response
exit status 1
```

In the config log I just see 'failed' but in the column 'Configuration Path" I can see **vsys vsys1 address z_host_1.1.1.1** (which is correct object) instead of **device-group MR-DC1-PROD address z_host_1.2.3.4** which is the case when I do it manually with set command on the device itself

**Comment by scottdware** [comment]
I just tested it against Panorama and a local device, and didn't get any errors. Can you send me a sample of your csv file? I know there have been issues before with the incorrect format, so just make sure that you're "saving as" a csv file.

**Comment by irom77** [comment]
See my csv file below. But it works with firewall, I just change IP (from Panorama address to firewall address) and it is fine:

```
z_host_1.1.1.1,ip,1.1.1.1,,
z_host_1.1.1.2,ip,1.1.1.2,,
z_host_1.1.1.3,ip,1.1.1.3,,
z_host_1.1.1.4,ip,1.1.1.4,,
```

Also this is not only for CreateAddressFromCsv method , when I try CreateAddress I have the same problem (with Panorama only).

**Comment by scottdware** [comment]
So only when specifying a device group?

**Comment by irom77** [comment]
Yep, in fact I was able to print p.URI, , xpath and responses when IP is set to Panorama , see below 10.34.2.149 (doesnt look like deive group is set to my MR-DC1-PROD):

```
https://10.34.2.149/api/?type=config&action=set&xpath=/config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/address/entry[@name='z_address']&elem
ent=<ip-netmask>1.2.3.4/32</ip-netmask>&key=XXX
<response status="error" code="13"><msg><line>Could not find schema node for xpath /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/address/entry[@name='z_address']
</line></msg></response>
2017/03/22 10:51:04 error code 13: Operation failed - A descriptive error message is returned in the response
exit status 1
```

and when ip is set to firewall 192.168.3.101:

```
https://192.168.3.101/api/?type=config&action=set&xpath=/config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/address/entry[@name='z_address']&element=<ip-netmask>1.2.3.4/32</ip-netmask>&key=XXX
<response status="success" code="20"><msg>command succeeded</msg></response>
```

**Comment by irom77** [comment]
When I create address object from curl , I can see path has /device-group/entry[@name='MR-DC1-PROD'] in Panorama not /vsys/entry[@name='vsys1'] which is good only for firewall

```
curl -kg "https://10.34.2.149/api/?type=config&action=set&xpath=/config/devices/entry
[@name='localhost.localdomain']/device-group/entry[@name='MR-DC1-PROD']/address/entry
[@name='test_address_3']&element=<ip-netmask>1.2.3.4/32</ip-
netmask>&key=XXX"
<response status="success" code="20"><msg>command succeeded</msg></response>

```

**Comment by scottdware** [comment]
After you connect to your Panorama server, can you print out the following and paste it here:

```Go
fmt.Printf("%+v\n", pan) // or whatever variable you are using
```

**Comment by irom77** [comment]
Here it is (replaced api by XXX, and serial by YYY) : 

```
{Host:10.34.2.149 Key:XXX URI:https://10.34.2.149/api/? Platform:pc Model:Panorama Serial:YYY SoftwareVersion:7.1.7 DeviceType:panos Panorama:false}
```

**Comment by scottdware** [comment]
And you're sure this is the Panorama server? Cause what you linked shows me that it's picking it up as a "panos" device type, and not "panorama." What type of device is this (virtual, etc.)

**Comment by irom77** [comment]
Yes it is Panorama running on VM ( ESXi server )

```
admin@Panorama> show system info
hostname: Panorama
ip-address: 10.34.2.149
netmask: 255.255.255.0
default-gateway: 10.34.2.1
ipv6-address: unknown
ipv6-link-local-address: fe80::250:56ff:feb5:ffc6/64
ipv6-default-gateway: 
mac-address: 00:50:56:b5:yy:xx
time: Wed Mar 22 13:13:20 2017
uptime: 25 days, 9:13:04
family: pc
model: Panorama
serial: 000702956yyy
sw-version: 7.1.7
app-version: 564-3168
app-release-date: unknown
av-version: 0
av-release-date: unknown
wf-private-version: 0
wf-private-release-date: unknown
url-db: paloaltonetworks
logdb-version: 7.0.9
platform-family: pc
system-mode: panorama
operational-mode: normal
```

It says system-mode: panorama, model: Panorama too

**Comment by scottdware** [comment]
Ok, then that was the problem. I've never tested this against a VM series, so I will correct that logic in the code and publish it.

**Comment by scottdware** [comment]
Ok, I just updated the repo. Go ahead and try it again (you might have to run `go get -u github.com/scottdware/go-panos` again, but I don't think so).

**Comment by irom77** [comment]
You improved it faster than I would ever imagine, works perfectly ! Thnx again, appreciate

**Comment by scottdware** [comment]
Great! Thanks so much for providing this feedback. VM was something that I never had a chance to test against, so I'm glad that you were able to help with that!
