### ISSUE TITLE
Issue with applying Vulnerability security profile 

### ISSUE THREAD

**Issue by rexshang** [scottdware/go-panos#7]
I was browsing through code and come across this pattern in panos.go:1623.  Note that AntiSpyware string was used as Vulnerability.  The same pattern repeated in other places in the same file.  Can you check if this is intended?  Thanks.

`if len(secprofiles.Vulnerability) > 0 {
						xmlBody += fmt.Sprintf("<vulnerability><member>%s</member></vulnerability>", secprofiles.AntiSpyware)
					}`

**Comment by scottdware** [comment]
Ah, thanks for finding this. Probably forgot to change the values when I copied certain parts!

**Comment by rexshang** [comment]
No problem.  Thank you for your effort maintaining this!  Btw, do you have any sample code for security profile creation for antivirus or vulnerability?

Cheers,

Rex

**Comment by scottdware** [comment]
Ok, fixed the typo, and also added the ability to apply URL filtering and file-blocking profiles as well.

As for examples on profile creation, that is something that I'm working on currently, so I should have the ability to create profiles finished soon!

**Comment by rexshang** [comment]
Very cool.  Looking forward to see the new capabilities.

Rex
