### ISSUE TITLE
cannot use Shared (type bool) as type string in argument to pan1session.CreateAddressFromCsv

### ISSUE THREAD

**Issue by irom77** [scottdware/go-panos#8]
I am getting error in using bool arg in pan1session.CreateAddressFromCsv(file, Shared, Devicegroup). Was it depreciated ? I can see only string spread in spec now ?

```
# github.com/IrekRomaniuk/pan-cli/cmd
go/src/github.com/IrekRomaniuk/pan-cli/cmd/load.go:52: cannot use Shared (type bool) as type string in argument to pan1session.CreateAddressFromCsv
```

**Comment by scottdware** [comment]
I changed the way shared objects are created, which made it a bit easier to deal with. I'll post a description about it in the README a bit later, and let you know when it's posted.

Basically, there's a SetShared() function which tells your session that now everything you create from that point on is shared. You can call it again to turn it off (has a true/false parameter).

**Comment by scottdware** [comment]
Ok, I've put section in the README on the main page that describes this change, and how to handle the creation of shared objects.
